apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapipreview
  labels:
    app: strapipreview
  namespace: namespace-workflow-1708489276685
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strapipreview
  template:
    metadata:
      labels:
        app: strapipreview
    spec:
      containers:
        - name: strapipreview
          image: acrworkflow1708489276685.azurecr.io/image-workflow-1708489276685:latest
          ports:
            - containerPort: 3000