apiVersion: v1
kind: Service
metadata:
  name: strapipreview
  namespace: namespace-workflow-1708489276685
spec:
  type: LoadBalancer
  selector:
    app: strapipreview
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000