apiVersion: v1
kind: Service
metadata:
  name: strapi-test
  namespace: namespace-workflow-1708487295964
spec:
  type: LoadBalancer
  selector:
    app: strapi-test
  ports:
    - protocol: TCP
      port: 1337
      targetPort: 1337